### ISSUE TITLE
Several problems about the code

### ISSUE THREAD

**Issue by likuanppd** [VITA-Group/ProgressiveDD#2]
Hi authors, thanks for this interesting and inspiring work.

I'm having a few issues while running the code distill_mtt.py.

1. The commands for CIFAR-10 in the README.md seem to have IPC=10 and IPC=50 mixed up.
```
# IPC=10 (P=5)
CUDA_VISIBLE_DEVICES=0 python distill_mtt.py --dataset=CIFAR10 --model=ConvNet --ipc=10 --syn_steps=30 --expert_epochs=2 --max_start_epoch=15 --zca --lr_img=1000 --lr_lr=1e-05 --lr_teacher=0.01 --num_intervals 5 --root_log_dir logged_files

# IPC=50 (P=5)
CUDA_VISIBLE_DEVICES=0 python distill_mtt.py --dataset=CIFAR10 --model=ConvNet --ipc=2 --syn_steps=50 --expert_epochs=2 --max_start_epoch=5 --zca --lr_img=1000 --lr_lr=1e-07 --lr_teacher=0.01 --num_intervals 5 --root_log_dir logged_files 
```

2. Some arguments don't seem to be used, which results in some redundant lines in the code. For example, start_sampling_epoch is always 0, merge-interval and filter-correct-samples are never set to True, and difficulty-interval doesn't appear in the code, etc.

3. Some arguments are inconsistent in their declaration and usage, like some are declared with a dash but used with an underscore in the code. Also, many arguments lack comments, making the code a bit hard to read. 

4. I tried running the CIFAR-10 IPC=10 code but encountered an error at line 275. The error message is shown below. It seems like there's no buffer in the save_dir after entering the second interval. ```
File "/home/xxx/Experiments/baselines/ProgressiveDD/./distill_mtt.py", line 275, in main
    raise AssertionError("No buffers detected at {}".format(expert_dir))
AssertionError: No buffers detected at ./logged_files/CIFAR10/CIFAR10_ConvNet_S_ipc2_max5_syn50_real2_img1000.0_1e-07_0.01_increase_zca/interval1_epoch1-5
```

Thanks for your help.

Best regards

**Comment by xxchenxx** [comment]
Thanks for your interests.

For Q1, I will update the commands today. Thanks for pointing out.

For Q2, those arguments were used before in our experiments, but not in use anymore now. I will remove them.

For Q3, they are not inconsistent but a feature (or let’s say a constraint) since we cannot use dash in variable names.

For Q4, the codes seem to be fine on my side. Could you confirm there are files under that folder, and the first interval is indeed finished? Thanks!

**Comment by likuanppd** [comment]
Thanks for your prompt reply.

Yes, the first interval is finished and the files in the logged_files are shown bellow:
![image](https://github.com/VITA-Group/ProgressiveDD/assets/48855254/b261f467-deda-46f3-905f-5c1ec5645965)

In the second interval, args.buffer_path changes to the logged_files. The buffer is loaded in line 271-273, but I find there are no "replay_buffer_{n}.pt"  stored in the logged_files. 

```
while os.path.exists(os.path.join(expert_dir, "replay_buffer_{}.pt".format(n))):
    expert_files.append(os.path.join(expert_dir, "replay_buffer_{}.pt".format(n)))
    n += 1
```
I didn't modify anything of the code, and just try to run it by the provided commands.

**Comment by xxchenxx** [comment]
Yeah that is unexpected. What did the log files show? It seems that the buffer generation process did not start..

**Comment by xxchenxx** [comment]
I just cropped the end of the log from wandb: 

3575 Itr: 99 Epoch: 7 Train Acc: 0.69 Test Acc: 0.7034
3576 Saving ./logs/CIFAR10/CIFAR10_ConvNet_S_ipc2_max5_syn50_real2_img1000.0_1e-07_0.01_increase_zca/interval1_epoch1-5/replay_buffer_9.pt
3577 Evaluate 100 random ConvNet, mean = 0.5272 std = 0.0076

Could you confirm if you can see something similar?

**Comment by likuanppd** [comment]
I think I know why I encounter this issue and I will try it again. Thanks for your help! To be honest, this is really a promising work but I feel some pain when I read the code hhhh. It would be much better if there are more comments.

**Comment by xxchenxx** [comment]
Thanks! 

We have plans to improve & accelerate the code (hopefully recently). Please stay tuned! And you can check out the provided checkpoints & distilled images (for evaluation, if that's what you need)

Best,
